name: gcp-mlops-stack-mlflow-vm
provider:
  name: gcp
  project_id: hatchet14
  region: us-west2
  zone: us-west2-a

cost_analysis:
  enabled: true              # Enable/disable cost analysis (default: true)
  warning_threshold: 50.0    # Warn if monthly cost exceeds this amount (default: 100.0)
  currency: "USD"   

deployment:
  type: cloud_vm

stack:
  - experiment_tracking:
      name: mlflow
      params:
        # service_name: mlflow-server-vm
        service_name: mlflow-server-postgres-vm # for postgres backend
        # vm_name: mlflow-vm-instance
        vm_name: mlflow-postgres-vm-instance # for postgres backend
        machine_type: e2-medium
        disk_size_gb: 20
        mlflow_port: 5000
        allow_public_access: true
        # FastAPI configuration
        fastapi_port: 8000
        fastapi_app_source: "template"  # or "gs://bucket/path.py" or "/local/path.py"
  - artifact_tracking:
      name: mlflow
      params: 
        # artifact_bucket: mlflow-artifact-bucket-vm-54321
        artifact_bucket: mlflow-artifact-bucket-postgres-2
        create_artifact_bucket: true
  - model_registry:
      name: mlflow
      params: 
        # backend_store_uri: sqlite:///mlflow.db  # SQLite backend (local file)
        backend_store_uri: postgresql # for postgres backend
  - feature_store:
      name: feast
      params: 
        service_name: feast-server
        feast_port: 6566
        backend_store_uri: postgresql  # Uses same PostgreSQL as MLflow
        registry_type: sql  # or "file" for development
        online_store_type: sqlite  # sqlite, datastore, bigtable
        offline_store_type: bigquery
        bigquery_dataset: feast_offline_store
        create_bigquery_dataset: true
        sample_data: false  # Set to true to create sample sales data table
  - model_monitoring:
      name: grafana
      params: 
        service_name: grafana-server
        enable_grafana: true
        grafana_port: 3000
        grafana_admin_user: admin
        grafana_admin_password: admin
  - workflow_orchestration:
      name: airflow
      params:
        service_name: airflow-server
        airflow_port: 8080
        airflow_worker_port: 8793
        airflow_flower_port: 5555
        backend_store_uri: postgresql
        airflow_database_name: airflow
        airflow_database_user: airflow
        airflow_separate_database: true
        airflow_admin_user: admin
        airflow_admin_password: admin123
        airflow_executor: LocalExecutor
        airflow_parallelism: 4
        airflow_dag_concurrency: 2
        airflow_max_active_runs_per_dag: 2
        airflow_webserver_workers: 1  # Set to 1 worker to fix child process issues
